spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    driver-class-name: org.postgresql.Driver
    username: books
    password: books
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    prefix: classpath:/client/templates/
